import type { Game } from "./types";

export const demoGames: Game[] = [
  { name: "Gloomhaven", weight: "heavy" },
  { name: "Pandemic Legacy Season 1", weight: "heavy" },
  { name: "Brass: Birmingham", weight: "heavy" },
  { name: "Twilight Imperium: Fourth Edition", weight: "heavy" },
  { name: "Spirit Island", weight: "heavy" },
  { name: "Ark Nova", weight: "heavy" },
  { name: "Dune: Imperium", weight: "heavy" },
  { name: "Gloomhaven: Jaws of the Lion", weight: "heavy" },
  { name: "Wingspan", weight: "heavy" },
  { name: "7 Wonders Duel", weight: "light" },
  { name: "The Crew: The Quest for Planet Nine", weight: "light" },
  { name: "Everdell", weight: "heavy" },
  { name: "Blood Rage", weight: "heavy" },
  { name: "Star Wars: Rebellion", weight: "heavy" },
  { name: "Mage Knight", weight: "heavy" },
  { name: "Codenames", weight: "light" },
  { name: "7 Wonders", weight: "heavy" },
  { name: "Pandemic", weight: "heavy" },
  { name: "Splendor", weight: "light" },
  { name: "Azul", weight: "light" },
  { name: "Project L", weight: "light" },
  { name: "Patchwork", weight: "light" },
  { name: "The Lord of the Rings: Journeys in Middle-Earth", weight: "heavy" },
  { name: "Eldritch Horror", weight: "heavy" },
  { name: "Sleeping Gods: Distant Skies", weight: "heavy" },
  { name: "Mansions of Madness", weight: "heavy" },
  { name: "Oath: Chronicles of Empire and Exile", weight: "heavy" },
  { name: "Arkham Horror", weight: "heavy" },
  { name: "Star Wars: Imperial Assault", weight: "heavy" },
  { name: "Betrayal at House on the Hill", weight: "heavy" },
  { name: "Codenames: Duet", weight: "light" },
  { name: "Flamecraft", weight: "light" },
  { name: "Sagrada", weight: "light" },
  { name: "Kingdomino", weight: "light" },
  { name: "The Search for Planet X", weight: "heavy" },
  { name: "Mysterium", weight: "light" },
  { name: "Dixit", weight: "light" },
  { name: "Photosynthesis", weight: "heavy" },
  { name: "PARKS", weight: "light" },
  { name: "Wavelength", weight: "light" },
  { name: "Santorini", weight: "light" },
  { name: "Star Realms", weight: "light" },
  { name: "Hanabi", weight: "light" },
  { name: "The Mind", weight: "light" },
  { name: "Dice Forge", weight: "light" },
  { name: "Blokus", weight: "light" },
  { name: "Camel Up", weight: "light" },
  { name: "Carcassone", weight: "light" },
  { name: "Roll for the Galaxy", weight: "light" },
  { name: "Evolution: Climate", weight: "light" },
  { name: "Champions of Midgard", weight: "heavy" },
  { name: "Takenoko", weight: "light" },
  { name: "Sheriff of Nottingham", weight: "light" },
  { name: "Tiny Epic Galaxies", weight: "light" },
  { name: "The Resistance", weight: "light" },
  { name: "Space Base", weight: "light" },
  { name: "Above and Below", weight: "heavy" },
  { name: "Near and Far", weight: "heavy" },
  { name: "Tsuro", weight: "light" },
  { name: "Incan Gold", weight: "light" },
  { name: "Qwixx", weight: "light" },
  { name: "Roll For It!", weight: "light" },
  { name: "Forbidden Island", weight: "light" },
  { name: "Machi Koro", weight: "light" },
  { name: "Tokaido", weight: "light" },
  { name: "Settlers of Catan", weight: "light" },
  { name: "Dead of Winter: A Crossroads Game", weight: "heavy" },
  { name: "Seasons", weight: "heavy" },
  { name: "Flash Point", weight: "heavy" },
  { name: "Ghost Stories", weight: "heavy" },
  { name: "Elder Sign", weight: "heavy" },
  { name: "Clank! In! Space!", weight: "heavy" },
  { name: "Dice Throne Adventures", weight: "heavy" },
  { name: "Mechs vs. Minions", weight: "heavy" },
  { name: "The Fox in the Forest", weight: "light" },
  { name: "Harry Potter: Hogwarts Battle", weight: "light" },
  { name: "Fury of Dracula", weight: "heavy" },
  { name: "Last Night on Earth", weight: "heavy" },
  { name: "Anomia", weight: "light" },
  { name: "Telestrations", weight: "light" },
  { name: "Concept", weight: "light" },
  { name: "So Clover!", weight: "light" },
  { name: "Medium", weight: "light" },
  { name: "5-Minute Dungeon", weight: "light" },
  { name: "5-Minute Mystery", weight: "light" },
  { name: "Throw Throw Burrito", weight: "light" },
  { name: "Throw Throw Avocado", weight: "light" },
  { name: "Taco Cat Goat Cheese Pizza", weight: "light" },
  { name: "Alice is Missing", weight: "light" },
  { name: "Blokus Duo", weight: "light" },
  { name: "Cat in the Box", weight: "light" },
  { name: "Celestia", weight: "light" },
  { name: "Chicken!", weight: "light" },
  { name: "Chimera", weight: "light" },
  { name: "Chocobo's Crystal Hunt", weight: "light" },
  { name: "Crypt", weight: "light" },
  { name: "Dark Souls", weight: "heavy" },
  { name: "DC Comics Deck-Building Game: Forever Evil", weight: "heavy" },
  { name: "Deep Space D-6: Armada", weight: "heavy" },
  { name: "Dice Throne (Season 2 Battlechest)", weight: "heavy" },
  { name: "Dice Throne Season 1: Rerolled (Ninja / Treant)", weight: "heavy" },
  { name: "Disturbed Friends", weight: "light" },
  { name: "Dungeon Roll", weight: "light" },
  { name: "Evolution: The Beginning", weight: "light" },
  { name: "Flash Duel", weight: "light" },
  { name: "Flipships", weight: "light" },
  { name: "Floating Floors", weight: "light" },
  { name: "Glow", weight: "light" },
  { name: "Horizons of Spirit Island", weight: "heavy" },
  { name: "Hot Ones Truth or Dab", weight: "light" },
  { name: "In Tenebris Lux", weight: "heavy" },
  { name: "Inoka", weight: "light" },
  { name: "Koryo", weight: "light" },
  { name: "Machi Koro 2", weight: "light" },
  { name: "Middara: Unintentional Malum", weight: "heavy" },
  { name: "Misdirection", weight: "light" },
  { name: "Namiji", weight: "light" },
  { name: "Night of the Ninja", weight: "light" },
  { name: "No Escape", weight: "light" },
  { name: "Overseers", weight: "light" },
  { name: "Pandante", weight: "light" },
  { name: "Pandemic Hot Zone North America", weight: "light" },
  { name: "Planet", weight: "light" },
  { name: "Primal: The Awakening", weight: "heavy" },
  { name: "Puzzle Strike", weight: "heavy" },
  { name: "Ramen Fury", weight: "light" },
  { name: "Reavers of Midgard", weight: "heavy" },
  { name: "Risk - Starcraft Edition", weight: "heavy" },
  { name: "Rummikub", weight: "light" },
  { name: "Sabobatage", weight: "light" },
  { name: "Samurai Spirit", weight: "light" },
  { name: "Scream: The Game", weight: "light" },
  { name: "Set a Watch", weight: "heavy" },
  { name: "Shinobi Clans", weight: "light" },
  { name: "Smart Ass", weight: "light" },
  { name: "Space Invaders", weight: "light" },
  { name: "Star Wars: X-Wing", weight: "heavy" },
  { name: "Starving Artists", weight: "light" },
  { name: "Street Masters", weight: "heavy" },
  { name: "Tags", weight: "light" },
  { name: "Tavern Trouble", weight: "light" },
  { name: "The Lord of the Rings: The Card Game", weight: "heavy" },
  { name: "The Shared Dream", weight: "heavy" },
  { name: "Tiny Towns", weight: "light" },
  { name: "Trickster", weight: "light" },
  { name: "Ultra Tiny Epic Galaxies", weight: "light" },
  { name: "Ultra Tiny Epic Kingdoms", weight: "light" },
  { name: "Uno", weight: "light" },
  { name: "Volfyirion", weight: "light" },
  { name: "Yashima: Legend of the Kami Masters", weight: "heavy" },
  { name: "Yokai Septet", weight: "light" },
  { name: "Yomi", weight: "light" },
  { name: "Monopoly Knockout", weight: "light" },
  { name: "Steam Up: A Feast of Dim Sum", weight: "light" },
  { name: "Dice Miner", weight: "light" },
  { name: "Thunder Road: Vendetta", weight: "light" },
  { name: "Super Boss Monster", weight: "light" },
  { name: "Lure", weight: "light" },
  { name: "Pride of Ninja", weight: "light" },
  { name: "Chroma Arcana", weight: "heavy" },
  { name: "Staccs", weight: "light" },
  { name: "Flip 7", weight: "light" },
  { name: "TowerBrix", weight: "light" },
  { name: "Moonrollers", weight: "light" },
  { name: "Veiled Fate", weight: "heavy" },
  { name: "Fellowships of Fate", weight: "light" },
  { name: "Zeni Hajiki", weight: "light" },
  { name: "The Night Cage", weight: "heavy" },
  { name: "Paku Paku", weight: "light" },
  { name: "Kabuto Sumo: Sakura Slam", weight: "light" },
  { name: "A Game of Thrones: B'Twixt", weight: "heavy" },
  { name: "Beast", weight: "heavy" },
  { name: "Alibis", weight: "light" },
  { name: "Agricola: All Creatures Big and Small", weight: "heavy" },
];